# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(db_index=True, max_length=200)),
                ('platform', models.CharField(db_index=True, max_length=7)),
                ('price', models.FloatField()),
                ('appstore', models.CharField(max_length=200)),
                ('redirect_url', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('app_icon', models.TextField()),
                ('app_image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adnetwork.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adnetwork.Click')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=20)),
                ('gender', models.CharField(max_length=6)),
                ('device_ifa', models.CharField(db_index=True, max_length=200)),
                ('device_anroid_id', models.CharField(db_index=True, max_length=200)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='click',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adnetwork.User'),
        ),
    ]
